apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinicapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinicapp
  template:
    metadata:
      labels:
        app: petclinicapp
    spec:
      containers:
      - name: petclinicapp
        image: balumahendran.azurecr.io/balumahendran:latest
        imagePullPolicy: Always
        
